@startuml Appointment Scheduler Class Diagram

namespace domain {

    class TimeSlot {
        + DateTime Date
        + DateTime FromTime
        + DateTime ToTime
    }

    class Appointment {
        + DateTime Date
        + DateTime FromTime
        + DateTime ToTime
        + String ClientId
        + String MedicalPractionerId
        + String Description
        + String Reason
    }

    class MedicalPractioner {
        + String MedicalPractionerId
        + String Name
    }

    class Client {
        + String ClientId
        + String Name
    }

    Appointment -d-> TimeSlot
    Appointment -d-> Client
    Appointment -d-> MedicalPractioner
}

namespace service {

    class Scheduler {
        Appointment ScheduleAppointment(Appointment)
    }

    class Calendar {
        TimeSlot FindNextTimeSlot(MedicalPractionerId)
    }
}

namespace repository {

    class AppointmentRepository {
        Appointment SaveAppointment(Appointment)
        void DeleteAppointment(AppointmentId)
    }

}

' domain -d-> service
' service -d-> repository

@enduml